#pragma once

#include "Core.h"
#include "GameEngine.h"
#include "EntryPoint.h"
#include "src/GameEvent.h"
#include "src/EngineContext.h"
#include "src/AssetManager.h"
#include "src/InputManager.h"
#include "src/Camera.h"

#include "src/sdl/SDLEventDispatcher.h"
#include "src/sdl/SDLEventHandler.h"

#include "src/ecs/CollisionMatrix.h"
#include "src/ecs/EntityManager.h"
#include "src/ecs/SystemPriority.h"
#include "src/ecs/component/AnimationComponent.h"
#include "src/ecs/component/ColliderComponent.h"
#include "src/ecs/component/SpriteComponent.h"
#include "src/ecs/component/TransformComponent.h"
#include "src/ecs/component/VelocityComponent.h"
#include "src/ecs/system/AnimationSystem.h"
#include "src/ecs/system/CollisionSystem.h"
#include "src/ecs/system/MovementSystem.h"
#include "src/ecs/system/RenderSystem.h"

#include "src/ui/Widget.h"
#include "src/ui/Theme.h"
#include "src/ui/layout/BoxContainer.h"
#include "src/ui/layout/HorizontalBox.h"
#include "src/ui/layout/VerticalBox.h"
#include "src/ui/display/Panel.h"
#include "src/ui/display/Text.h"
#include "src/ui/display/Image.h"
#include "src/ui/input/Button.h"
#include "src/ui/input/Checkbox.h"
#include "src/ui/input/Scalar.h"
#include "src/ui/input/Dropdown.h"
#include "src/ui/input/TextInput.h"
#include "src/ui/Canvas.h"
