#pragma once

#include "Core.h"
#include "GameEngine.h"
#include "EntryPoint.h"
#include "src/GameEvent.h"
#include "src/EngineContext.h"
#include "src/AssetManager.h"
#include "src/InputManager.h"
#include "src/Camera.h"

#include "src/sdl/SDLEventDispatcher.h"
#include "src/sdl/SDLEventHandler.h"

#include "src/ecs/EntityManager.h"
#include "src/ecs/component/AnimationComponent.h"
#include "src/ecs/component/SpriteComponent.h"
#include "src/ecs/component/TransformComponent.h"
#include "src/ecs/component/VelocityComponent.h"
#include "src/ecs/system/AnimationSystem.h"

#include "src/ui/Widget.h"
#include "src/ui/BoxContainer.h"
#include "src/ui/HorizontalBox.h"
#include "src/ui/VerticalBox.h"
#include "src/ui/Panel.h"
#include "src/ui/Text.h"
#include "src/ui/Image.h"
#include "src/ui/Button.h"
#include "src/ui/Canvas.h"
